# question_data = [
#     {"text": "Operační systém Linux byl založen Linusem Torvaldem", "answer": "True"},
#     {"text": "HTML jazyk je také nazýván značkovacím jazykem", "answer": "True"},
#     {"text": "JavaScript patří mezi frontendové jazyky", "answer": "True"},
#     {"text": "CSS je programovací jazyk", "answer": "False"},
# ]
question_data = [
    {
        "category": "History",
        "type": "boolean",
        "difficulty": "medium",
        "question": "The M41 Walker Bulldog remains in service in some countries to this day.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "History",
        "type": "boolean",
        "difficulty": "hard",
        "question": "The Kingdom of Prussia briefly held land in Estonia.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "History",
        "type": "boolean",
        "difficulty": "easy",
        "question": "The United States was a member of the League of Nations.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "History",
        "type": "boolean",
        "difficulty": "medium",
        "question": "Theodore Roosevelt Jr. was the only General involved in the initial assault on D-Day.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "History",
        "type": "boolean",
        "difficulty": "easy",
        "question": "The United States of America declared their independence from the British Empire on July 4th, 1776.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "History",
        "type": "boolean",
        "difficulty": "medium",
        "question": "Oxford University is older than the Aztec Empire. ",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "History",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Adolf Hitler was tried at the Nuremberg trials.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "History",
        "type": "boolean",
        "difficulty": "hard",
        "question": "The USS Missouri (BB-63) last served in the Korean War.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "History",
        "type": "boolean",
        "difficulty": "medium",
        "question": "The Korean War ended in 1953 without any ceasefire.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "History",
        "type": "boolean",
        "difficulty": "medium",
        "question": "Franz Joseph I was the last emperor of Austria.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
]
